parameters:
    json_schema.validator.class: JsonSchema\Validator
    json_schema.validator.service.class: HadesArchitect\JsonSchemaBundle\Validator\ValidatorService

    json_schema.uri_resolver.class: JsonSchema\Uri\UriResolver
    json_schema.uri_resolver.service.class: HadesArchitect\JsonSchemaBundle\Uri\UriResolverService

    json_schema.uri_retriever.class: JsonSchema\Uri\UriRetriever
    json_schema.uri_retriever.service.class: HadesArchitect\JsonSchemaBundle\Uri\UriRetrieverService

services:

    hades.json_schema.validator:
        class: %json_schema.validator.service.class%
        arguments: [%json_schema.validator.class%]

    hades.json_schema.uri_resolver:
        class: %json_schema.uri_resolver.service.class%
        arguments: [%json_schema.uri_resolver.class%]

    hades.json_schema.uri_retriever:
        class: %json_schema.uri_retriever.service.class%
        arguments: [%json_schema.uri_retriever.class%]
