language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3
  - SYMFONY_VERSION=2.4
  - SYMFONY_VERSION=2.5
  - SYMFONY_VERSION=2.6
  - SYMFONY_VERSION=2.7
  - SYMFONY_VERSION=2.8
  - SYMFONY_VERSION=3.0
  - SYMFONY_VERSION=3.1
  - JSONSCHEMA_VERSION=1
  - JSONSCHEMA_VERSION=2
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer require justinrainbow/json-schema:${JSONSCHEMA_VERSION}

script: phpunit --coverage-text

notifications:
  email: "a.volochnev@gmail.com"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
